Fix remove version and handle slash in title
Beam-Connectivity/grafana-dashboard-manager pull request #16
Opened 2023-01-31 11:06 UTC by julienlau

This evolution contains 2 features : 
- it remove the grafana version from the json file written to disks whel downloading all dashboards
- it fix a bug where dashboard that contain a "/" in their title are currently ignored.

2023-09-03 01:10 UTC, anarcat commented on README.md
> +can be disabled with the option `skip-home`.
this seems like an unrelated change.

2023-09-03 01:11 UTC, anarcat requested changes

2023-09-03 01:11 UTC, anarcat commented on README.md
> +- The "/" in the title of the dashboard are now supported.
this seems to only be a documentation update, where is the related code fix for this? also, does this fix #13?

2023-12-28 23:24 UTC, chan-vince commented
The cli has been rewritten and includes your change to remove the `version`, but its popped when writing dashboard files back to Grafana, rather than when downloading them. While this does mean you might have a bigger git diff, it's also important in our opinion that the `download` saves the json files _exactly_ as they are in Grafana which is why it's done on upload. I hope this makes sense :)

2023-12-28 23:24 UTC, closed without merging